package com.nevzatcirak.sharedsignals.core.privacy;

/**
 * SSF Privacy Considerations Documentation.
 * <p>
 * This class documents privacy considerations and best practices
 * as per SSF Specification Section 10.
 * <p>
 * <b>10.1 Subject Information Leakage:</b>
 * <ul>
 *   <li>Always use the same Subject Identifier Type for a given subject/receiver pair</li>
 *   <li>Example: If you identify user@example.com as "email" to ReceiverA, always use "email" format</li>
 *   <li>Don't mix identifier types (email, phone, opaque) for the same subject to the same receiver</li>
 *   <li>This prevents correlation attacks where receiver could link different identifiers</li>
 * </ul>
 * <p>
 * <b>10.2 Previously Consented Data:</b>
 * <ul>
 *   <li>If data was previously shared with receiver, no additional consent needed</li>
 *   <li>Exception: One-time consent - if consent was for single use, don't reuse</li>
 *   <li>Track which attributes have been shared with each receiver</li>
 *   <li>Example: If email was shared during OAuth flow, it can be included in events</li>
 * </ul>
 * <p>
 * <b>10.3 New Data:</b>
 * <ul>
 *   <li><b>Organizational Data:</b> Data generated by transmitter (e.g., risk scores, login counts)
 *       can be shared if user agreed to third-party sharing in terms of service</li>
 *   <li><b>Consentable Data:</b> Personal data not previously shared requires explicit consent</li>
 *   <li>Examples requiring consent: New phone number, new address, biometric data</li>
 *   <li>Consent must be obtained per transmitter's privacy policy and regulations (GDPR, CCPA, etc.)</li>
 * </ul>
 * <p>
 * <b>Implementation Guidelines:</b>
 * <pre>{@code
 * // 1. Implement your own PrivacyPolicyValidator
 * public class MyPrivacyValidator implements PrivacyPolicyValidator {
 *
 *     @Override
 *     public PrivacyValidationResult validateEventSharing(...) {
 *         // Check consent management system
 *         if (!consentService.hasConsent(subject, receiver, eventType)) {
 *             return PrivacyValidationResult.denied("No consent");
 *         }
 *
 *         // Check data classification
 *         if (containsConsentableData(eventDetails)) {
 *             if (!hasExplicitConsent(subject, receiver)) {
 *                 return PrivacyValidationResult.denied("New consentable data");
 *             }
 *         }
 *
 *         return PrivacyValidationResult.allowed();
 *     }
 * }
 *
 * // 2. Register your validator as a Spring Bean
 * @Bean
 * public PrivacyPolicyValidator privacyPolicyValidator() {
 *     return new MyPrivacyValidator();
 * }
 * }</pre>
 * <p>
 * <b>Integration with Consent Management Systems:</b>
 * <ul>
 *   <li>OneTrust</li>
 *   <li>TrustArc</li>
 *   <li>Osano</li>
 *   <li>Custom consent databases</li>
 * </ul>
 *
 * @see PrivacyPolicyValidator
 * @see DefaultPrivacyPolicyValidator
 * @see <a href="https://datatracker.ietf.org/doc/html/draft-ietf-secevent-sharedsignals#section-10">SSF Spec Section 10</a>
 */
public final class PrivacyConsiderations {
    private PrivacyConsiderations() {
        // Documentation class - no instantiation
    }

    /**
     * Example subject identifier formats that should be consistent per receiver.
     */
    public enum SubjectIdentifierConsistency {
        /**
         * Good: Always use email format for a given user to a given receiver.
         */
        CONSISTENT_EMAIL("email", "user@example.com"),

        /**
         * Bad: Mixing email and phone for the same user to the same receiver.
         * This allows correlation.
         */
        INCONSISTENT_MIXED("email/phone", "user@example.com OR +1234567890");

        private final String format;
        private final String example;

        SubjectIdentifierConsistency(String format, String example) {
            this.format = format;
            this.example = example;
        }

        public String getFormat() {
            return format;
        }

        public String getExample() {
            return example;
        }
    }

    /**
     * Example data classifications for consent management.
     */
    public enum DataClassification {
        /**
         * Previously shared data - no additional consent needed.
         */
        PREVIOUSLY_CONSENTED,

        /**
         * Organizational data - can be shared per TOS agreement.
         */
        ORGANIZATIONAL,

        /**
         * New consentable data - requires explicit consent.
         */
        CONSENTABLE_NEW
    }
}