package com.nevzatcirak.sharedsignals.api.enums;

public enum SecurityIntent {
    // CAEP
    SESSION_REVOKED, SESSION_ESTABLISHED, SESSION_PRESENTED,
    CREDENTIAL_CHANGE, TOKEN_CLAIMS_CHANGE,
    ASSURANCE_LEVEL_CHANGE, DEVICE_COMPLIANCE_CHANGE, RISK_LEVEL_CHANGE,

    // RISC
    ACCOUNT_DISABLED, ACCOUNT_ENABLED, ACCOUNT_PURGED,
    CREDENTIAL_COMPROMISE, ACCOUNT_CREDENTIAL_CHANGE_REQUIRED,
    IDENTIFIER_CHANGED, IDENTIFIER_RECYCLED,
    OPT_OUT, RECOVERY_ACTIVATED, RECOVERY_INFORMATION_CHANGED,

    // SSF Control
    VERIFICATION
}
